REDIS_PRODUCTIVITY_HOST = 'aristotle-test.dotcloud.com'
REDIS_PRODUCTIVITY_PORT = 6379
REDIS_ACCESS_HOST = 'aristotle-test.dotcloud.com'
REDIS_ACCESS_PORT = 6379
REDIS_DB = 0
REDIS_TEST_DB = 1
REDIS_PASSWORD = "11112222"
CALL_NUMBER_DB = 4
